package com.lastminute.exception;

/**
 * Class which manages all the general exception generated by the program
 * @author Tiziano
 *
 */
public class LastMinuteException extends Exception {

	private static final long serialVersionUID = -6159039702523104776L;

	/**
	 * General message error given by the system
	 * @param message
	 */
	public LastMinuteException(String message) {
		super(message);
	}
}
